In [3]:
from keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [4]:
import numpy as np
import random
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [5]:
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential

In [6]:
np.shape(y_test)

(10000,)

In [7]:
nx_train=np.reshape(x_train,(60000, 28*28))
nx_test=np.reshape(x_test,(10000, 28*28))
nx_train = nx_train/255.0
nx_test = nx_test/255.0
print(nx_train)
#ny_train=np.reshape(y_train,(60000, 28*28))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [8]:
pca = PCA(n_components=0.97)
newx_train= pca.fit_transform(nx_train)
newx_test = pca.transform(nx_test)
#newy_train = pca.transform(y_train)
print(newx_train.shape)

(60000, 214)


In [9]:
clf = SVC()
clf.fit(newx_train, y_train)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [10]:
print("訓練資料辨識率:",np.mean(clf.predict(newx_train) == y_train))

訓練資料辨識率: 0.9702833333333334


In [94]:
newx_test

array([[-2.95429410e+00,  6.26767802e-02, -8.68021367e-01, ...,
         1.76543489e-05, -5.79062409e-03, -8.70352033e-03],
       [-2.94064111e+00,  6.29507860e-02, -8.58473446e-01, ...,
        -8.78605413e-04, -5.14373054e-03, -8.44935288e-03],
       [-2.95699740e+00,  7.35164175e-02, -8.70543408e-01, ...,
         1.45315182e-03, -5.89541322e-03, -8.73423808e-03],
       ...,
       [-2.95893825e+00,  6.99470989e-02, -8.71606128e-01, ...,
        -2.60084734e-04, -5.54867896e-03, -9.05937508e-03],
       [-2.95419147e+00,  6.73993073e-02, -8.59741895e-01, ...,
         5.65843700e-04, -5.10544603e-03, -9.14547420e-03],
       [-2.95886724e+00,  6.71051610e-02, -8.59093525e-01, ...,
         8.96847680e-05, -6.19333786e-03, -9.41874876e-03]])

In [11]:
print("測試資料辨識率:",np.mean(clf.predict(newx_test) == y_test))

測試資料辨識率: 0.9656
